# -*- coding: utf-8 -*-
"""Nutrition Analytics _Data Scraping_Data Science Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIfm70MjTdWw-PBjrfSBQzVLV3Z72wwk
"""

# ============================================================
#  Nutrition Analytics Scraper — Google Colab version
#  Source: https://www.nutritionvalue.org  (Beautiful Soup only)
# ============================================================
#
#  HOW TO RUN IN COLAB:
#  1. Ekta cell-e ei pura code paste koro.
#  2. Run koro. Sesh hole file download hobe automatically.
#  (Colab-e requests, bs4, pandas already installed thake.)
#
# ============================================================

import re
import time
import string
from urllib.parse import urljoin

import requests
import pandas as pd
from bs4 import BeautifulSoup

# ---- Settings (icche mole change korte paro) ----
TARGET = 2000        # koto record chao
DELAY = 1.0          # protiti request-er majhe delay (second). Colab-e 1.0 rakho.
OUT_FILE = "nutrition_dataset.csv"

BASE_URL = "https://www.nutritionvalue.org"
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (compatible; DataScienceLab-NutritionScraper/1.0; "
        "educational research project)"
    )
}

COLUMNS = [
    "Food Name", "Food Category", "Serving Size (g)", "Calories (kcal)",
    "Protein (g)", "Total Fat (g)", "Carbohydrates (g)", "Fiber (g)",
    "Sugar (g)", "Sodium (mg)", "Cholesterol (mg)", "Potassium (mg)",
]

NUTRIENT_MAP = {
    "protein":      ("Protein (g)",       "g"),
    "fat":          ("Total Fat (g)",     "g"),
    "carbohydrate": ("Carbohydrates (g)", "g"),
    "fiber":        ("Fiber (g)",         "g"),
    "sugars":       ("Sugar (g)",         "g"),
    "sodium":       ("Sodium (mg)",       "mg"),
    "cholesterol":  ("Cholesterol (mg)",  "mg"),
    "potassium":    ("Potassium (mg)",    "mg"),
}

DETAIL_RE = re.compile(r"_\d+_nutritional_value\.html$")


def get_soup(session, url, max_retries=3):
    """URL fetch kore BeautifulSoup return kore, retry soho."""
    for attempt in range(1, max_retries + 1):
        try:
            resp = session.get(url, headers=HEADERS, timeout=30)
            if resp.status_code == 200:
                return BeautifulSoup(resp.text, "html.parser")
            if resp.status_code == 404:
                return None
            print(f"  [{resp.status_code}] {url} (attempt {attempt})")
        except requests.RequestException as exc:
            print(f"  [error] {exc} (attempt {attempt})")
        time.sleep(2 * attempt)
    return None


def collect_food_urls(session, target, delay):
    """A-Z listing page theke food detail-page URL joma kore."""
    frontier, seen = [], set()
    goal = int(target * 1.6)

    for letter in string.ascii_uppercase:
        page_url = f"{BASE_URL}/foods_start_with_{letter}.html"
        page_num = 1
        while page_url:
            soup = get_soup(session, page_url)
            if soup is None:
                break
            found = 0
            for a in soup.find_all("a", href=True):
                if DETAIL_RE.search(a["href"]):
                    full = urljoin(BASE_URL, a["href"])
                    if full not in seen:
                        seen.add(full)
                        frontier.append(full)
                        found += 1
            print(f"[frontier] {letter} p{page_num}: +{found} (total {len(frontier)})")
            if len(frontier) >= goal:
                return frontier
            nxt = soup.find("a", string=re.compile(r"^\s*Next\s*$"))
            page_url = urljoin(BASE_URL, nxt["href"]) if nxt else None
            page_num += 1
            time.sleep(delay)
    return frontier


def _to_float(text):
    if text is None:
        return None
    m = re.search(r"-?\d+(?:\.\d+)?", text.replace(",", ""))
    return float(m.group()) if m else None


def parse_food_page(soup, url):
    """Ekta food page theke ek row extract kore (per 100 g normalised)."""
    page_text = soup.get_text(" ", strip=True)

    name = None
    h1 = soup.find("h1")
    if h1 and h1.get_text(strip=True):
        name = h1.get_text(strip=True)
    if not name and soup.title:
        name = re.sub(r"\s*nutrition facts and analysis\.?\s*$", "",
                      soup.title.get_text(strip=True), flags=re.I)
    if not name:
        return None
    name = name.strip()

    portion_g = None
    m = re.search(r"Portion Size\s*([\d.]+)\s*g", page_text)
    if not m:
        m = re.search(r"\(([\d.]+)\s*g\)", page_text)
    if m:
        portion_g = float(m.group(1))
    if not portion_g or portion_g <= 0:
        portion_g = 100.0
    factor = 100.0 / portion_g

    calories = None
    m = re.search(r"([\d.]+)\s*Calories", page_text)
    if not m:
        m = re.search(r"Calories\s*([\d.]+)", page_text)
    if m:
        calories = float(m.group(1))

    values = {}
    for row in soup.find_all("tr"):
        cells = row.find_all("td")
        if len(cells) < 2:
            continue
        label = cells[0].get_text(" ", strip=True).lower()
        amount_txt = cells[1].get_text(" ", strip=True)
        for key, (col, unit) in NUTRIENT_MAP.items():
            if re.match(rf"^{key}\b", label) and col not in values:
                val = _to_float(amount_txt)
                if val is not None:
                    values[col] = val
                break

    category = None
    for row in soup.find_all("tr"):
        cells = row.find_all("td")
        if len(cells) >= 2 and cells[0].get_text(strip=True).lower() == "category":
            category = cells[1].get_text(" ", strip=True)
            break

    record = {c: None for c in COLUMNS}
    record["Food Name"] = name
    record["Food Category"] = category
    record["Serving Size (g)"] = 100
    record["Calories (kcal)"] = round(calories * factor, 1) if calories is not None else None
    for col in NUTRIENT_MAP.values():
        colname = col[0]
        if colname in values:
            record[colname] = round(values[colname] * factor, 3)

    if record["Calories (kcal)"] is None and all(
        record[c] is None for c in ("Protein (g)", "Total Fat (g)", "Carbohydrates (g)")
    ):
        return None
    return record


def clean_dataframe(records, target):
    df = pd.DataFrame(records, columns=COLUMNS)
    before = len(df)

    numeric_cols = [c for c in COLUMNS if c not in ("Food Name", "Food Category")]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df["Food Name"] = df["Food Name"].astype(str).str.strip()
    df["Food Category"] = df["Food Category"].fillna("Unknown").str.strip()

    df = df[df["Food Name"].str.len() > 0]
    df = df.dropna(subset=["Calories (kcal)"])

    df = df.drop_duplicates(
        subset=["Food Name", "Calories (kcal)", "Protein (g)",
                "Carbohydrates (g)", "Total Fat (g)"]
    )
    df = df.drop_duplicates().reset_index(drop=True)

    if target and len(df) > target:
        df = df.iloc[:target].copy()

    print(f"[clean] {before} raw -> {len(df)} clean ({before - len(df)} removed)")
    return df


# ------------------- MAIN -------------------
session = requests.Session()

print("STAGE 1: URL collect kora hocche...")
urls = collect_food_urls(session, TARGET, DELAY)
print(f"\nTotal {len(urls)} URL paoa gyeche.\n")

print("STAGE 2: detail page scrape kora hocche...")
records = []
for i, url in enumerate(urls, 1):
    soup = get_soup(session, url)
    if soup is not None:
        rec = parse_food_page(soup, url)
        if rec:
            records.append(rec)
    if i % 50 == 0:
        print(f"  {i}/{len(urls)} pages -> {len(records)} records")
    time.sleep(DELAY)

print(f"\n{len(records)} raw record paoa gyeche.\n")

print("STAGE 3: clean kore CSV banano hocche...")
df = clean_dataframe(records, TARGET)
df.to_csv(OUT_FILE, index=False)

print("\n----- DATASET SUMMARY -----")
print("Records :", len(df))
print("Columns :", len(df.columns))
print("Missing values per column:")
print(df.isna().sum().to_string())

# Colab-e file download kore dey
try:
    from google.colab import files
    files.download(OUT_FILE)
    print(f"\n'{OUT_FILE}' download suru hoyeche.")
except Exception:
    print(f"\nFile saved: {OUT_FILE}")